package org.anytest.logger.enums;

public enum LogType {
    PASS,
    FAIL,
    SKIP,
    FATAL,
    TRACE,
    PASS_EXTENT_AND_LOG,
    FAIL_EXTENT_AND_LOG,
    SKIP_EXTENT_AND_LOG,
    INFO_EXTENT_AND_LOG,

    PASS_EXTENT_WITH_LABEL,
    FAIL_EXTENT_WITH_LABEL,
    SKIP_EXTENT_WITH_LABEL,
    INFO_EXTENT_WITH_LABEL

}
